export type PlantCategory = 'Sombra' | 'Meia-Sombra' | 'Sol Pleno' | 'Suculenta';
export type Difficulty = 'Fácil' | 'Médio' | 'Difícil';

export interface PlantMetric {
  value: string;
  level: number;
}

export interface Plant {
  id: string;
  name: string;
  scientificName: string;
  category: PlantCategory;
  difficulty: Difficulty;
  petFriendly: boolean;
  image: string;
  description: string;
  tags: string[];
  specs: {
    light: PlantMetric;
    water: PlantMetric;
    temperature: PlantMetric;
    soil: PlantMetric;
  };
  careGuide: string[];
}

export const categoryFilters: { label: string; value: string }[] = [
  { label: 'Todas', value: 'todas' },
  { label: 'Sombra', value: 'Sombra' },
  { label: 'Meia-Sombra', value: 'Meia-Sombra' },
  { label: 'Sol Pleno', value: 'Sol Pleno' },
  { label: 'Suculentas', value: 'Suculenta' },
  { label: 'Fácil Cuidado', value: 'facil-cuidado' },
  { label: 'Pet Friendly', value: 'pet-friendly' },
];

export const plants: Plant[] = [
  {
    id: 'monstera-deliciosa',
    name: 'Costela-de-Adão',
    scientificName: 'Monstera deliciosa',
    category: 'Meia-Sombra',
    difficulty: 'Médio',
    petFriendly: false,
    image: 'https://images.pexels.com/photos/36477236/pexels-photo-36477236.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'A rainha das plantas tropicais, famosa por suas folhas perfuradas gigantes que trazem um ar de floresta úmida para qualquer ambiente.',
    tags: ['Trepadeira', 'Folhagem Gigante', 'Tropical'],
    specs: {
      light: { value: 'Luz indireta forte, sem sol direto', level: 3 },
      water: { value: 'A cada 7-10 dias, solo seco entre regas', level: 3 },
      temperature: { value: '18°C – 27°C', level: 3 },
      soil: { value: 'Substrato leve e bem drenado com fibra de coco', level: 3 },
    },
    careGuide: [
      'Posicione perto de uma janela com luz filtrada, longe do sol do meio-dia.',
      'Deixe os primeiros 3-4 cm do solo secarem antes de regar novamente.',
      'Limpe as folhas com pano úmido a cada 2 semanas para manter os poros livres.',
      'Ofereça um suporte (moss pole) para as raízes aéreas se fixarem e a planta crescer vertical.',
    ],
  },
  {
    id: 'ficus-robusta',
    name: 'Ficus Robusta',
    scientificName: 'Ficus elastica robusta',
    category: 'Meia-Sombra',
    difficulty: 'Fácil',
    petFriendly: false,
    image: 'https://images.pexels.com/photos/29518481/pexels-photo-29518481.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Folhas grossas, brilhantes e resistentes que dão um toque escultural e sofisticado a qualquer cômodo.',
    tags: ['Folhagem', 'Purifica o Ar', 'Decoração'],
    specs: {
      light: { value: 'Luz indireta brilhante', level: 3 },
      water: { value: 'A cada 7-9 dias no verão, menos no inverno', level: 2 },
      temperature: { value: '16°C – 26°C', level: 3 },
      soil: { value: 'Substrato rico com boa drenagem', level: 3 },
    },
    careGuide: [
      'Escolha um local iluminado, evitando correntes de vento frio.',
      'Regue somente quando os primeiros centímetros do solo estiverem secos.',
      'Gire o vaso a cada semana para um crescimento uniforme em direção à luz.',
      'Aplique adubo balanceado a cada 2 meses durante a primavera e o verão.',
    ],
  },
  {
    id: 'queijo-suico',
    name: 'Queijo-Suíço',
    scientificName: 'Monstera adansonii',
    category: 'Sombra',
    difficulty: 'Médio',
    petFriendly: false,
    image: 'https://images.pexels.com/photos/37064202/pexels-photo-37064202.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Prima menor da Monstera deliciosa, com folhas rendadas cheias de furos, perfeita para vasos suspensos.',
    tags: ['Trepadeira', 'Vaso Suspenso', 'Compacta'],
    specs: {
      light: { value: 'Luz indireta média a forte', level: 3 },
      water: { value: 'A cada 6-8 dias', level: 3 },
      temperature: { value: '18°C – 29°C', level: 3 },
      soil: { value: 'Substrato aerado com perlita', level: 3 },
    },
    careGuide: [
      'Cultive em cesto suspenso ou com suporte para valorizar o crescimento em cascata.',
      'Mantenha a umidade do ar alta com borrifadas leves nas folhas.',
      'Regue quando a camada superior do substrato estiver seca ao toque.',
      'Pode as pontas para estimular ramificações mais cheias.',
    ],
  },
  {
    id: 'pilea-peperomioides',
    name: 'Pilea Peperomioides',
    scientificName: 'Pilea peperomioides',
    category: 'Meia-Sombra',
    difficulty: 'Fácil',
    petFriendly: true,
    image: 'https://images.pexels.com/photos/7180559/pexels-photo-7180559.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Conhecida como "planta-do-dinheiro-chinesa", suas folhas redondas e brilhantes são puro charme minimalista.',
    tags: ['Pet Friendly', 'Compacta', 'Moderna'],
    specs: {
      light: { value: 'Luz indireta brilhante', level: 4 },
      water: { value: 'A cada 6-7 dias', level: 3 },
      temperature: { value: '15°C – 25°C', level: 2 },
      soil: { value: 'Substrato leve e bem drenado', level: 3 },
    },
    careGuide: [
      'Rotacione o vaso semanalmente para que cresça de forma simétrica.',
      'Regue profundamente e espere o solo secar entre as regas.',
      'Remova os "filhotes" que brotam na base para propagar novas mudas.',
      'Evite encharcamento, que é a causa mais comum de apodrecimento das raízes.',
    ],
  },
  {
    id: 'zamioculca',
    name: 'Zamioculca',
    scientificName: 'Zamioculcas zamiifolia',
    category: 'Sombra',
    difficulty: 'Fácil',
    petFriendly: false,
    image: 'https://images.pexels.com/photos/10651639/pexels-photo-10651639.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'A planta perfeita para iniciantes: folhas verde-escuras cerosas que sobrevivem a semanas de esquecimento.',
    tags: ['Baixa Manutenção', 'Resistente', 'Ambientes Internos'],
    specs: {
      light: { value: 'Tolera pouca luz a luz indireta', level: 1 },
      water: { value: 'A cada 14-21 dias', level: 1 },
      temperature: { value: '18°C – 30°C', level: 4 },
      soil: { value: 'Substrato bem drenado tipo cactos', level: 2 },
    },
    careGuide: [
      'Regue apenas quando o solo estiver completamente seco.',
      'Tolera cantos escuros do escritório ou apartamento sem sofrer.',
      'Evite excesso de água, os rizomas armazenam água como tubérculos.',
      'Limpe as folhas ocasionalmente para realçar seu brilho natural.',
    ],
  },
  {
    id: 'alocasia-polly',
    name: 'Alocasia Polly',
    scientificName: 'Alocasia × amazonica',
    category: 'Meia-Sombra',
    difficulty: 'Difícil',
    petFriendly: false,
    image: 'https://images.pexels.com/photos/31964238/pexels-photo-31964238.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Folhas em forma de seta com nervuras brancas marcantes, um verdadeiro item de destaque para colecionadores.',
    tags: ['Folhagem Exótica', 'Estatement', 'Colecionável'],
    specs: {
      light: { value: 'Luz indireta brilhante e filtrada', level: 3 },
      water: { value: 'A cada 5-7 dias, manter úmido sem encharcar', level: 4 },
      temperature: { value: '18°C – 27°C', level: 3 },
      soil: { value: 'Substrato aerado, rico em matéria orgânica', level: 4 },
    },
    careGuide: [
      'Mantenha alta umidade do ar com um umidificador ou bandeja de água.',
      'Regue assim que a superfície do solo secar, nunca deixe secar por completo.',
      'Proteja de correntes de ar frio e mudanças bruscas de temperatura.',
      'É normal perder folhas no inverno; reduza a rega neste período.',
    ],
  },
  {
    id: 'filodendro-brasil',
    name: 'Filodendro Brasil',
    scientificName: 'Philodendron hederaceum "Brasil"',
    category: 'Sombra',
    difficulty: 'Fácil',
    petFriendly: false,
    image: 'https://images.pexels.com/photos/17665056/pexels-photo-17665056.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Folhas em formato de coração com listras douradas vibrantes, ótima trepadeira para prateleiras e estantes.',
    tags: ['Trepadeira', 'Folhagem Colorida', 'Iniciantes'],
    specs: {
      light: { value: 'Luz indireta média', level: 3 },
      water: { value: 'A cada 7 dias', level: 3 },
      temperature: { value: '18°C – 26°C', level: 3 },
      soil: { value: 'Substrato universal com drenagem', level: 2 },
    },
    careGuide: [
      'Quanto mais luz indireta receber, mais vibrantes ficam as listras douradas.',
      'Deixe o solo secar levemente entre uma rega e outra.',
      'Pode facilmente ser propagada por estaquia em água.',
      'Guie os ramos em um suporte para um efeito mais cheio e vertical.',
    ],
  },
  {
    id: 'maranta-pavao',
    name: 'Maranta Pavão',
    scientificName: 'Maranta leuconeura',
    category: 'Sombra',
    difficulty: 'Médio',
    petFriendly: true,
    image: 'https://images.pexels.com/photos/2894960/pexels-photo-2894960.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Conhecida como "planta que reza", suas folhas se dobram à noite e exibem um padrão pintado à mão.',
    tags: ['Pet Friendly', 'Folhas Decorativas', 'Movimento'],
    specs: {
      light: { value: 'Luz indireta média a baixa', level: 2 },
      water: { value: 'A cada 5-6 dias, solo sempre levemente úmido', level: 4 },
      temperature: { value: '18°C – 25°C', level: 3 },
      soil: { value: 'Substrato rico e retentor de umidade', level: 3 },
    },
    careGuide: [
      'Use água filtrada ou de chuva para evitar manchas nas pontas das folhas.',
      'Mantenha o substrato sempre levemente úmido, nunca encharcado.',
      'Borrife água nas folhas para simular seu habitat tropical úmido.',
      'Observe o movimento das folhas: se fecharem de dia, falta luz ou água.',
    ],
  },
  {
    id: 'planta-jade',
    name: 'Planta-Jade',
    scientificName: 'Crassula ovata',
    category: 'Suculenta',
    difficulty: 'Fácil',
    petFriendly: false,
    image: 'https://images.pexels.com/photos/26932353/pexels-photo-26932353.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Suculenta símbolo de prosperidade, com folhas espessas e brilhantes que armazenam água como pequenas jóias.',
    tags: ['Suculenta', 'Sorte', 'Baixa Manutenção'],
    specs: {
      light: { value: 'Sol direto pela manhã ou luz forte', level: 5 },
      water: { value: 'A cada 12-15 dias', level: 1 },
      temperature: { value: '18°C – 28°C', level: 3 },
      soil: { value: 'Substrato para cactos e suculentas', level: 1 },
    },
    careGuide: [
      'Exponha a bastante luz para manter o caule firme e compacto.',
      'Regue profundamente e deixe secar completamente entre as regas.',
      'Pode ser facilmente propagada a partir de uma folha destacada.',
      'Em vasos, garanta furos de drenagem para evitar apodrecimento.',
    ],
  },
  {
    id: 'caladio',
    name: 'Caládio',
    scientificName: 'Caladium bicolor',
    category: 'Sombra',
    difficulty: 'Médio',
    petFriendly: false,
    image: 'https://images.pexels.com/photos/23079347/pexels-photo-23079347.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Folhas em forma de coração pintadas em tons de rosa, branco e verde, um espetáculo de cor para a sombra.',
    tags: ['Folhagem Colorida', 'Sazonal', 'Jardim'],
    specs: {
      light: { value: 'Sombra a meia-sombra, sem sol direto', level: 2 },
      water: { value: 'A cada 4-5 dias, manter úmido', level: 4 },
      temperature: { value: '20°C – 29°C', level: 4 },
      soil: { value: 'Substrato rico e fértil, sempre úmido', level: 4 },
    },
    careGuide: [
      'Cultive em local sombreado e protegido de vento forte.',
      'Mantenha o solo sempre úmido, nunca encharcado, durante o crescimento.',
      'É normal perder as folhas no inverno; o tubérculo entra em dormência.',
      'Reduza a rega quando as folhas começarem a murchar naturalmente.',
    ],
  },
  {
    id: 'lambari-roxo',
    name: 'Lambari-Roxo',
    scientificName: 'Tradescantia zebrina',
    category: 'Meia-Sombra',
    difficulty: 'Fácil',
    petFriendly: false,
    image: 'https://images.pexels.com/photos/8610779/pexels-photo-8610779.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Trepadeira de crescimento rápido com folhas listradas em roxo metálico e prata, perfeita para vasos suspensos.',
    tags: ['Trepadeira', 'Roxo Vibrante', 'Crescimento Rápido'],
    specs: {
      light: { value: 'Luz indireta brilhante para manter a cor', level: 4 },
      water: { value: 'A cada 5-6 dias', level: 3 },
      temperature: { value: '16°C – 26°C', level: 3 },
      soil: { value: 'Substrato universal bem drenado', level: 2 },
    },
    careGuide: [
      'Quanto mais luz, mais intensas ficam as cores roxas das folhas.',
      'Pode os ramos regularmente para manter a planta cheia e compacta.',
      'Propague facilmente por estaquia direto em água ou substrato.',
      'Regue quando a superfície do solo estiver seca ao toque.',
    ],
  },
  {
    id: 'fitonia',
    name: 'Fitônia',
    scientificName: 'Fittonia albivenis',
    category: 'Sombra',
    difficulty: 'Médio',
    petFriendly: true,
    image: 'https://images.pexels.com/photos/17874650/pexels-photo-17874650.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Pequena planta de folhas verdes com nervuras brancas ou rosa marcantes, ideal para terrários e mesas.',
    tags: ['Pet Friendly', 'Terrário', 'Nervuras Marcantes'],
    specs: {
      light: { value: 'Luz indireta média a baixa', level: 2 },
      water: { value: 'A cada 3-4 dias, solo sempre úmido', level: 4 },
      temperature: { value: '18°C – 26°C', level: 3 },
      soil: { value: 'Substrato leve e retentor de umidade', level: 3 },
    },
    careGuide: [
      'Mantenha alta umidade, ideal para terrários fechados ou banheiros.',
      'Nunca deixe o solo secar completamente, ela murcha rapidamente.',
      'Se murchar, regue e ela geralmente se recupera em poucas horas.',
      'Evite sol direto, que queima suas folhas finas e delicadas.',
    ],
  },
  {
    id: 'dracena',
    name: 'Dracena',
    scientificName: 'Dracaena fragrans',
    category: 'Meia-Sombra',
    difficulty: 'Fácil',
    petFriendly: false,
    image: 'https://images.pexels.com/photos/28889277/pexels-photo-28889277.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Tronco ereto com folhas longas em roseta, uma escolha clássica e resistente para escritórios e salas.',
    tags: ['Purifica o Ar', 'Decoração', 'Baixa Manutenção'],
    specs: {
      light: { value: 'Luz indireta média', level: 3 },
      water: { value: 'A cada 9-12 dias', level: 2 },
      temperature: { value: '18°C – 27°C', level: 3 },
      soil: { value: 'Substrato universal bem drenado', level: 2 },
    },
    careGuide: [
      'Tolera ambientes internos com pouca luz natural, ideal para escritórios.',
      'Regue com moderação, o excesso causa pontas marrons nas folhas.',
      'Use água filtrada, a Dracena é sensível ao flúor da torneira.',
      'Remova folhas amareladas na base para manter a aparência saudável.',
    ],
  },
  {
    id: 'flor-de-cera',
    name: 'Flor-de-Cera',
    scientificName: 'Hoya carnosa',
    category: 'Meia-Sombra',
    difficulty: 'Fácil',
    petFriendly: false,
    image: 'https://images.pexels.com/photos/35060562/pexels-photo-35060562.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Trepadeira suculenta com flores em forma de estrela, cerosas e perfumadas, que encantam por gerações.',
    tags: ['Flores', 'Suculenta', 'Aromática'],
    specs: {
      light: { value: 'Luz indireta forte para floração', level: 4 },
      water: { value: 'A cada 10-12 dias', level: 2 },
      temperature: { value: '18°C – 28°C', level: 3 },
      soil: { value: 'Substrato aerado com casca de pinus', level: 2 },
    },
    careGuide: [
      'Deixe o substrato secar bem entre regas, como uma suculenta.',
      'Não mova a planta durante a formação de botões, ela pode abortá-los.',
      'Ofereça um suporte para a trepadeira se enrolar conforme cresce.',
      'Após a floração, não corte os pedúnculos, novas flores nascem neles.',
    ],
  },
  {
    id: 'asplenio',
    name: 'Asplênio',
    scientificName: 'Asplenium nidus',
    category: 'Sombra',
    difficulty: 'Fácil',
    petFriendly: true,
    image: 'https://images.pexels.com/photos/37484960/pexels-photo-37484960.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Samambaia de ninho com folhas largas e onduladas que crescem em roseta, trazendo frescor tropical.',
    tags: ['Pet Friendly', 'Samambaia', 'Umidade'],
    specs: {
      light: { value: 'Sombra a luz indireta baixa', level: 2 },
      water: { value: 'A cada 5-6 dias, manter úmido', level: 4 },
      temperature: { value: '18°C – 27°C', level: 3 },
      soil: { value: 'Substrato rico em matéria orgânica', level: 3 },
    },
    careGuide: [
      'Regue diretamente no substrato, evitando acumular água no "ninho" central.',
      'Mantenha alta umidade do ar com borrifadas frequentes.',
      'Evite tocar as folhas novas enroladas no centro, são muito sensíveis.',
      'Ideal para banheiros e cozinhas com boa luminosidade indireta.',
    ],
  },
  {
    id: 'rosa-do-deserto',
    name: 'Rosa-do-Deserto',
    scientificName: 'Adenium obesum',
    category: 'Suculenta',
    difficulty: 'Médio',
    petFriendly: false,
    image: 'https://images.pexels.com/photos/34112988/pexels-photo-34112988.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Caudex engrossado e flores vibrantes em tons de rosa e vermelho, um bonsai natural cheio de personalidade.',
    tags: ['Flores', 'Suculenta', 'Bonsai'],
    specs: {
      light: { value: 'Sol pleno direto', level: 5 },
      water: { value: 'A cada 10-14 dias no verão', level: 1 },
      temperature: { value: '20°C – 32°C', level: 5 },
      soil: { value: 'Substrato arenoso de drenagem rápida', level: 1 },
    },
    careGuide: [
      'Ofereça o máximo de sol possível para uma floração generosa.',
      'Regue pouco e espere secar totalmente entre uma rega e outra.',
      'No inverno, reduza drasticamente a rega para evitar apodrecimento do caudex.',
      'Use vaso com muitos furos e substrato extremamente drenante.',
    ],
  },
  {
    id: 'jiboia',
    name: 'Jiboia',
    scientificName: 'Epipremnum aureum',
    category: 'Sombra',
    difficulty: 'Fácil',
    petFriendly: false,
    image: 'https://images.pexels.com/photos/11838530/pexels-photo-11838530.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'A trepadeira mais versátil que existe, com folhas em formato de coração salpicadas de dourado.',
    tags: ['Trepadeira', 'Purifica o Ar', 'Iniciantes'],
    specs: {
      light: { value: 'Tolera pouca luz a luz indireta forte', level: 2 },
      water: { value: 'A cada 7-9 dias', level: 2 },
      temperature: { value: '16°C – 28°C', level: 3 },
      soil: { value: 'Substrato universal bem drenado', level: 2 },
    },
    careGuide: [
      'Extremamente adaptável, cresce bem tanto em água quanto em terra.',
      'Deixe secar levemente entre regas para evitar raízes encharcadas.',
      'Pode os ramos para estimular uma copa mais cheia e ramificada.',
      'Ótima opção para pendurar em prateleiras altas ou treliças.',
    ],
  },
  {
    id: 'lanca-de-sao-jorge',
    name: 'Lança-de-São-Jorge',
    scientificName: 'Sansevieria cylindrica',
    category: 'Sol Pleno',
    difficulty: 'Fácil',
    petFriendly: false,
    image: 'https://images.pexels.com/photos/6279940/pexels-photo-6279940.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Folhas cilíndricas rígidas que se erguem como lanças, símbolo de proteção e extremamente resistente.',
    tags: ['Resistente', 'Proteção', 'Baixa Manutenção'],
    specs: {
      light: { value: 'Sol pleno a luz indireta', level: 4 },
      water: { value: 'A cada 14-18 dias', level: 1 },
      temperature: { value: '18°C – 30°C', level: 4 },
      soil: { value: 'Substrato para cactos e suculentas', level: 1 },
    },
    careGuide: [
      'Deixe o substrato secar completamente antes de regar novamente.',
      'Suporta sol pleno externo ou cantos internos com pouca luz.',
      'Evite molhar o centro das folhas para prevenir apodrecimento.',
      'Praticamente livre de pragas e ideal para quem viaja com frequência.',
    ],
  },
  {
    id: 'espada-de-sao-jorge',
    name: 'Espada-de-São-Jorge',
    scientificName: 'Sansevieria trifasciata',
    category: 'Sol Pleno',
    difficulty: 'Fácil',
    petFriendly: false,
    image: 'https://images.pexels.com/photos/3192175/pexels-photo-3192175.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Folhas largas e retas com faixas verde-escuras, uma das plantas mais resistentes e populares do Brasil.',
    tags: ['Resistente', 'Purifica o Ar', 'Tradicional'],
    specs: {
      light: { value: 'Sol pleno a sombra, muito adaptável', level: 4 },
      water: { value: 'A cada 15-20 dias', level: 1 },
      temperature: { value: '16°C – 30°C', level: 4 },
      soil: { value: 'Substrato para cactos e suculentas', level: 1 },
    },
    careGuide: [
      'Uma das plantas mais tolerantes, sobrevive a longos períodos sem água.',
      'Regue com moderação, o excesso é a principal causa de sua morte.',
      'Adapta-se tanto a ambientes internos escuros quanto a sol pleno.',
      'Divida a touceira a cada poucos anos para propagar novas mudas.',
    ],
  },
  {
    id: 'cacto-azeitona',
    name: 'Cacto-Azeitona',
    scientificName: 'Euphorbia tirucalli',
    category: 'Suculenta',
    difficulty: 'Fácil',
    petFriendly: false,
    image: 'https://images.pexels.com/photos/975018/pexels-photo-975018.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Hastes finas e verdes que formam uma copa arbustiva escultural, perfeita para composições modernas.',
    tags: ['Suculenta', 'Deserto', 'Escultural'],
    specs: {
      light: { value: 'Sol pleno direto', level: 5 },
      water: { value: 'A cada 12-16 dias', level: 1 },
      temperature: { value: '20°C – 32°C', level: 5 },
      soil: { value: 'Substrato arenoso de drenagem rápida', level: 1 },
    },
    careGuide: [
      'Use luvas ao manusear, sua seiva leitosa pode irritar a pele.',
      'Regue apenas quando o substrato estiver completamente seco.',
      'Ofereça o máximo de sol possível para um crescimento compacto.',
      'Evite ambientes com crianças ou pets pela toxicidade da seiva.',
    ],
  },
  {
    id: 'samambaia-americana',
    name: 'Samambaia-Americana',
    scientificName: 'Nephrolepis exaltata',
    category: 'Sombra',
    difficulty: 'Médio',
    petFriendly: true,
    image: 'https://images.pexels.com/photos/3854749/pexels-photo-3854749.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Folhagem exuberante e arqueada em tons de verde vivo, um clássico para varandas sombreadas e suspensas.',
    tags: ['Pet Friendly', 'Umidade', 'Samambaia'],
    specs: {
      light: { value: 'Sombra a meia-sombra', level: 2 },
      water: { value: 'A cada 3-4 dias, manter sempre úmida', level: 4 },
      temperature: { value: '16°C – 26°C', level: 3 },
      soil: { value: 'Substrato rico e retentor de umidade', level: 4 },
    },
    careGuide: [
      'Mantenha o substrato sempre úmido, nunca deixe secar por completo.',
      'Borrife água nas folhas diariamente, especialmente em dias secos.',
      'Proteja de vento forte e ar-condicionado, que ressecam suas folhas.',
      'Aduba mensalmente na primavera e verão para folhagem mais viçosa.',
    ],
  },
  {
    id: 'anturio',
    name: 'Antúrio',
    scientificName: 'Anthurium andraeanum',
    category: 'Meia-Sombra',
    difficulty: 'Médio',
    petFriendly: false,
    image: 'https://images.pexels.com/photos/12833554/pexels-photo-12833554.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Flores brilhantes em formato de coração que duram semanas, elegantes em qualquer ambiente interno.',
    tags: ['Flores', 'Elegante', 'Floração Longa'],
    specs: {
      light: { value: 'Luz indireta brilhante', level: 3 },
      water: { value: 'A cada 6-7 dias', level: 3 },
      temperature: { value: '18°C – 27°C', level: 3 },
      soil: { value: 'Substrato aerado e rico em matéria orgânica', level: 3 },
    },
    careGuide: [
      'Ofereça boa luminosidade indireta para estimular novas floradas.',
      'Regue quando a superfície do solo estiver seca ao toque.',
      'Remova flores murchas na base do caule para incentivar novas.',
      'Mantenha umidade do ar elevada com borrifadas regulares.',
    ],
  },
  {
    id: 'lirio-da-paz',
    name: 'Lírio-da-Paz',
    scientificName: 'Spathiphyllum wallisii',
    category: 'Sombra',
    difficulty: 'Fácil',
    petFriendly: false,
    image: 'https://images.pexels.com/photos/32425127/pexels-photo-32425127.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Flores brancas elegantes sobre folhagem verde-escura, uma das melhores plantas purificadoras de ar internas.',
    tags: ['Flores', 'Purifica o Ar', 'Iniciantes'],
    specs: {
      light: { value: 'Sombra a luz indireta baixa', level: 2 },
      water: { value: 'A cada 5-6 dias', level: 3 },
      temperature: { value: '18°C – 26°C', level: 3 },
      soil: { value: 'Substrato rico e retentor de umidade', level: 3 },
    },
    careGuide: [
      'As folhas caídas avisam quando está na hora de regar.',
      'Evite sol direto, que queima suas folhas facilmente.',
      'Limpe as folhas periodicamente para manter as trocas gasosas eficientes.',
      'Ótima escolha para banheiros e quartos com pouca luz natural.',
    ],
  },
  {
    id: 'begonia-maculata',
    name: 'Begônia-Maculata',
    scientificName: 'Begonia maculata',
    category: 'Meia-Sombra',
    difficulty: 'Médio',
    petFriendly: false,
    image: 'https://images.pexels.com/photos/4499368/pexels-photo-4499368.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Folhas em formato de asa com pintas prateadas e reverso vermelho intenso, uma verdadeira obra de arte viva.',
    tags: ['Folhagem Exótica', 'Instagramável', 'Colecionável'],
    specs: {
      light: { value: 'Luz indireta brilhante', level: 4 },
      water: { value: 'A cada 6-7 dias', level: 3 },
      temperature: { value: '18°C – 26°C', level: 3 },
      soil: { value: 'Substrato aerado e bem drenado', level: 3 },
    },
    careGuide: [
      'Regue apenas a base, evitando molhar as folhas para prevenir fungos.',
      'Mantenha boa circulação de ar ao redor da planta.',
      'Deixe o solo secar levemente na superfície entre regas.',
      'Propague facilmente por estaquia de caule em água.',
    ],
  },
  {
    id: 'peperomia',
    name: 'Peperômia',
    scientificName: 'Peperomia obtusifolia',
    category: 'Meia-Sombra',
    difficulty: 'Fácil',
    petFriendly: true,
    image: 'https://images.pexels.com/photos/38331731/pexels-photo-38331731.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Folhas carnudas e arredondadas em verde brilhante, compacta e perfeita para mesas e prateleiras pequenas.',
    tags: ['Pet Friendly', 'Compacta', 'Baixa Manutenção'],
    specs: {
      light: { value: 'Luz indireta média', level: 3 },
      water: { value: 'A cada 9-11 dias', level: 2 },
      temperature: { value: '18°C – 27°C', level: 3 },
      soil: { value: 'Substrato leve e bem drenado', level: 2 },
    },
    careGuide: [
      'Suas folhas carnudas armazenam água, então regue com moderação.',
      'Deixe o solo secar bem entre as regas para evitar apodrecimento.',
      'Ideal para espaços pequenos como mesas de trabalho e estantes.',
      'Propague facilmente por folhas ou estacas em substrato leve.',
    ],
  },
  {
    id: 'coleus',
    name: 'Coléus',
    scientificName: 'Coleus scutellarioides',
    category: 'Meia-Sombra',
    difficulty: 'Fácil',
    petFriendly: false,
    image: 'https://images.pexels.com/photos/36520167/pexels-photo-36520167.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Folhagem explosiva em vermelho, verde e roxo, ideal para dar cor instantânea a jardins e varandas.',
    tags: ['Folhagem Colorida', 'Exterior', 'Crescimento Rápido'],
    specs: {
      light: { value: 'Meia-sombra a luz indireta forte', level: 3 },
      water: { value: 'A cada 3-4 dias', level: 4 },
      temperature: { value: '18°C – 28°C', level: 3 },
      soil: { value: 'Substrato rico e retentor de umidade', level: 3 },
    },
    careGuide: [
      'Beliscar as pontas regularmente mantém a planta cheia e compacta.',
      'Não deixe o solo secar totalmente, suas folhas murcham rápido.',
      'Remova as flores para que a planta invista energia na folhagem.',
      'Proteja do sol forte do meio-dia para evitar folhas queimadas.',
    ],
  },
  {
    id: 'croton',
    name: 'Croton',
    scientificName: 'Codiaeum variegatum',
    category: 'Sol Pleno',
    difficulty: 'Médio',
    petFriendly: false,
    image: 'https://images.pexels.com/photos/11457407/pexels-photo-11457407.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Folhas ousadas em amarelo, laranja e vermelho, uma explosão tropical de cor que precisa de bastante luz.',
    tags: ['Folhagem Colorida', 'Tropical', 'Exterior'],
    specs: {
      light: { value: 'Sol pleno a luz indireta forte', level: 5 },
      water: { value: 'A cada 5-7 dias', level: 3 },
      temperature: { value: '18°C – 30°C', level: 4 },
      soil: { value: 'Substrato rico e bem drenado', level: 3 },
    },
    careGuide: [
      'Quanto mais luz receber, mais vibrantes ficam as cores das folhas.',
      'Mantenha regas regulares, mas sempre com boa drenagem.',
      'Evite mudanças bruscas de local, que causam queda de folhas.',
      'Borrife água nas folhas para manter a umidade em climas secos.',
    ],
  },
  {
    id: 'palmeira-rafis',
    name: 'Palmeira-Ráfis',
    scientificName: 'Rhapis excelsa',
    category: 'Meia-Sombra',
    difficulty: 'Médio',
    petFriendly: true,
    image: 'https://images.pexels.com/photos/12297326/pexels-photo-12297326.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Palmeira elegante de folhas leque profundamente segmentadas, perfeita para trazer um clima resort para casa.',
    tags: ['Pet Friendly', 'Palmeira', 'Elegante'],
    specs: {
      light: { value: 'Luz indireta média a forte', level: 3 },
      water: { value: 'A cada 7-9 dias', level: 3 },
      temperature: { value: '16°C – 27°C', level: 3 },
      soil: { value: 'Substrato rico com boa drenagem', level: 3 },
    },
    careGuide: [
      'Cresce lentamente, tenha paciência entre as trocas de vaso.',
      'Mantenha o solo levemente úmido, evitando encharcamento das raízes.',
      'Limpe as folhas periodicamente para remover poeira acumulada.',
      'Proteja de sol direto forte, que pode queimar as pontas das folhas.',
    ],
  },
  {
    id: 'jiboia-prateada',
    name: 'Jiboia-Prateada',
    scientificName: 'Scindapsus pictus',
    category: 'Sombra',
    difficulty: 'Fácil',
    petFriendly: false,
    image: 'https://images.pexels.com/photos/12079477/pexels-photo-12079477.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Folhas aveludadas verde-escuras salpicadas de prata metálica, uma trepadeira elegante e de baixa manutenção.',
    tags: ['Trepadeira', 'Prateada', 'Baixa Manutenção'],
    specs: {
      light: { value: 'Luz indireta média', level: 3 },
      water: { value: 'A cada 8-10 dias', level: 2 },
      temperature: { value: '18°C – 27°C', level: 3 },
      soil: { value: 'Substrato aerado e bem drenado', level: 2 },
    },
    careGuide: [
      'Deixe o solo secar bem entre as regas para evitar apodrecimento.',
      'Ótima opção para vasos suspensos ou treliças decorativas.',
      'Propague facilmente por estaquia direto em água.',
      'Tolera bem ambientes internos com iluminação moderada.',
    ],
  },
  {
    id: 'bico-de-papagaio',
    name: 'Bico-de-Papagaio',
    scientificName: 'Euphorbia pulcherrima',
    category: 'Sol Pleno',
    difficulty: 'Médio',
    petFriendly: false,
    image: 'https://images.pexels.com/photos/37347686/pexels-photo-37347686.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Brácteas vermelhas vibrantes que anunciam a chegada do fim de ano, um símbolo natalino cheio de vida.',
    tags: ['Flores', 'Sazonal', 'Exterior'],
    specs: {
      light: { value: 'Sol pleno a luz indireta forte', level: 4 },
      water: { value: 'A cada 6-8 dias', level: 3 },
      temperature: { value: '18°C – 28°C', level: 3 },
      soil: { value: 'Substrato rico e bem drenado', level: 3 },
    },
    careGuide: [
      'Ofereça bastante luz para intensificar a cor das brácteas.',
      'Regue quando a superfície do solo estiver seca, evitando encharcar.',
      'Após a floração, pode os ramos para estimular nova brotação.',
      'Sua seiva é tóxica, mantenha longe do alcance de crianças e pets.',
    ],
  },
];
